version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mongodb://db:27017/weather"
    depends_on:
      - db
    command: pytest && uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
